export const ApiErrorType = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  MISSING_API_KEY: "MISSING_API_KEY",
  INVALID_API_KEY: "INVALID_API_KEY",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
} as const;

export type ApiErrorType = (typeof ApiErrorType)[keyof typeof ApiErrorType];